<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SignIn</title>
</head>
<body>
<form action="/signIn" method="post">
    <label for="login">Enter login:
        <input id="login" name="login" placeholder="Login">
    </label>
    <label for="password">Enter password:
        <input id="password" name="password" placeholder="password">
    </label>
    <input type="submit" value="SignIn">
</form>
</body>
</html>